/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author vMp
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form Aii
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarDespesa1 = new javax.swing.JButton();
        btnIncluirReceita = new javax.swing.JButton();
        btnIncluirDespesa = new javax.swing.JButton();
        btnListarReceita = new javax.swing.JButton();
        btnListarDespesa = new javax.swing.JButton();
        btnConsultarSaldoData = new javax.swing.JButton();
        btnConsultarSaldo = new javax.swing.JButton();
        btnListarLancamento = new javax.swing.JButton();

        btnListarDespesa1.setText("Listar Despesa");
        btnListarDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDespesa1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIncluirReceita.setText("Incluir Receita");
        btnIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarIncluirReceita(evt);
            }
        });

        btnIncluirDespesa.setText("Incluir Despesa");
        btnIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarIncluirDespesa(evt);
            }
        });

        btnListarReceita.setText("Listar Receita");
        btnListarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarListarReceita(evt);
            }
        });

        btnListarDespesa.setText("Listar Despesa");
        btnListarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarListarDespesa(evt);
            }
        });

        btnConsultarSaldoData.setText("Consultar Saldo Até Data Atul");
        btnConsultarSaldoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarSaldoData(evt);
            }
        });

        btnConsultarSaldo.setText("Consultar Saldo Independente do Período");
        btnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarSaldoIndependente(evt);
            }
        });

        btnListarLancamento.setText("Listar Todos os Lançamentos");
        btnListarLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarListarLancamento(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIncluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIncluirDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnConsultarSaldoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(btnListarLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirDespesa)
                    .addComponent(btnIncluirReceita))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarReceita)
                    .addComponent(btnListarDespesa))
                .addGap(26, 26, 26)
                .addComponent(btnListarLancamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarSaldo)
                .addGap(12, 12, 12)
                .addComponent(btnConsultarSaldoData)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aoPressionarIncluirReceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarIncluirReceita
        this.setVisible(false);
        new IncluirReceita().setVisible(true);
    }//GEN-LAST:event_aoPressionarIncluirReceita

    private void aoPressionarListarReceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarListarReceita
        this.setVisible(false);
        new ListarReceita().setVisible(true);
    }//GEN-LAST:event_aoPressionarListarReceita

    private void aoPressionarListarDespesa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarListarDespesa
        this.setVisible(false);
        new ListarDespesa().setVisible(true);
    }//GEN-LAST:event_aoPressionarListarDespesa

    private void btnListarDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDespesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarDespesa1ActionPerformed

    private void aoPressionarSaldoData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarSaldoData
        this.setVisible(false);
        new SaldoData().setVisible(true);
    }//GEN-LAST:event_aoPressionarSaldoData

    private void aoPressionarSaldoIndependente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarSaldoIndependente
        this.setVisible(false);
        new SaldoIndependente().setVisible(true);
    }//GEN-LAST:event_aoPressionarSaldoIndependente

    private void aoPressionarListarLancamento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarListarLancamento
        this.setVisible(false);
        new ListarLancamento().setVisible(true);
    }//GEN-LAST:event_aoPressionarListarLancamento

    private void aoPressionarIncluirDespesa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarIncluirDespesa
        this.setVisible(false);
        new IncluirDespesa().setVisible(true);
    }//GEN-LAST:event_aoPressionarIncluirDespesa

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnConsultarSaldoData;
    private javax.swing.JButton btnIncluirDespesa;
    private javax.swing.JButton btnIncluirReceita;
    private javax.swing.JButton btnListarDespesa;
    private javax.swing.JButton btnListarDespesa1;
    private javax.swing.JButton btnListarLancamento;
    private javax.swing.JButton btnListarReceita;
    // End of variables declaration//GEN-END:variables
}
