/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import model.Despesa;
import model.Lancamento;
import model.Receita;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author vMp
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form Aii
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarDespesa1 = new javax.swing.JButton();
        btnIncluirReceita = new javax.swing.JButton();
        btnIncluirDespesa = new javax.swing.JButton();
        btnListarReceita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaDespesa = new javax.swing.JTable();

        btnListarDespesa1.setText("Listar Despesa");
        btnListarDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDespesa1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIncluirReceita.setText("Incluir Receita");
        btnIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarIncluirReceita(evt);
            }
        });

        btnIncluirDespesa.setText("Incluir Despesa");
        btnIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarIncluirDespesa(evt);
            }
        });

        btnListarReceita.setText("Listar Registro");
        btnListarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarListarReceita(evt);
            }
        });

        tbConsultaDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Registros"
            }
        ));
        jScrollPane1.setViewportView(tbConsultaDespesa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluirDespesa)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirDespesa)
                    .addComponent(btnIncluirReceita))
                .addGap(26, 26, 26)
                .addComponent(btnListarReceita)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aoPressionarIncluirReceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarIncluirReceita
        this.setVisible(false);
        new IncluirReceita().setVisible(true);
    }//GEN-LAST:event_aoPressionarIncluirReceita

    private void aoPressionarListarReceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarListarReceita
        DefaultTableModel modelo = (DefaultTableModel) tbConsultaDespesa.getModel();
        Lancamento l = new Lancamento();

        modelo.setRowCount(1);


        var modeloColuna = tbConsultaDespesa.getColumnModel();
        modeloColuna.getColumn(0).setPreferredWidth(100);

        for (String elemento : l.lerArquivo()) {

            String[] dados = elemento.split(";");

            modelo.addRow(dados);
        }
        
    }//GEN-LAST:event_aoPressionarListarReceita

    

    private void btnListarDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDespesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarDespesa1ActionPerformed


    private void aoPressionarIncluirDespesa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarIncluirDespesa
        this.setVisible(false);
        new IncluirDespesa().setVisible(true);
    }//GEN-LAST:event_aoPressionarIncluirDespesa

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluirDespesa;
    private javax.swing.JButton btnIncluirReceita;
    private javax.swing.JButton btnListarDespesa1;
    private javax.swing.JButton btnListarReceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultaDespesa;
    // End of variables declaration//GEN-END:variables
}
