/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CategoriaReceita;
import model.Lancamento;
import model.Pessoa;
import model.Receita;

/**
 *
 * @author vMp
 */
public class IncluirReceita extends javax.swing.JFrame {

    /**
     * Creates new form IncluirReceita
     */
    public IncluirReceita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        textFieldValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        textFieldDia = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        textFieldMes = new javax.swing.JTextField();
        textFieldAno = new javax.swing.JTextField();
        jLabelDia = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoPressionarVoltar(evt);
            }
        });

        jLabelTitle.setText("Incluir Receita");

        jLabelValor.setText("Valor: ");

        jLabelData.setText("Data: ");

        jLabelDia.setText("Dia:");

        jLabelMes.setText("Mês:");

        jLabelAno.setText("Ano:");

        jLabelCategoria.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "SALARIO", "DECIMO_TERCEIRO", "FERIAS", "OUTROS" }));
        
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnSalvarActionPerformed(evt);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Valor", "Data", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldValor)
                                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                                .addComponent(textFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCategoria)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelData))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDia)
                            .addComponent(jLabelMes)
                            .addComponent(jLabelAno))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aoPressionarVoltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoPressionarVoltar
        Pessoa pessoa = new Pessoa();
        List<Receita> listaReceitas = pessoa.ListarReceitas();

        // Agora você pode iterar sobre a lista de receitas e fazer o que precisar
        for (Receita receita : listaReceitas) {
            // Exemplo: exibir valor de cada receita
            System.out.println("Valor da Receita: " + receita.getValor());
        }

        this.setVisible(false);
        new App().setVisible(true);

    }//GEN-LAST:event_aoPressionarVoltar

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_btnSalvarActionPerformed
        // Botão Salvar
       try {
    if (textFieldValor.getText().isEmpty() || textFieldDia.getText().isEmpty()
            || textFieldMes.getText().isEmpty() || textFieldAno.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double valor = parseDouble(textFieldValor.getText());
    int dia = parseInt(textFieldDia.getText());
    int mes = parseInt(textFieldMes.getText());
    int ano = parseInt(textFieldAno.getText());
    String categoriaStr = jComboBoxCategoria.getSelectedItem().toString().toUpperCase();

    CategoriaReceita categoria = CategoriaReceita.valueOf(categoriaStr);

    if (mes < 1 || mes > 12 || dia < 1 || dia > 31) {
        JOptionPane.showMessageDialog(this, "Data inválida. Verifique os valores de dia e mês.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        return; // Retorna sem criar a data se a data for inválida
    }

    // Obter o modelo atual da tabela
    DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();

    // Adiciona a nova linha ao modelo da tabela
    for (int i = 0; i < 1; i++) { // Adiciona  receitas 
        LocalDate data = LocalDate.of(ano, mes, dia + i); // Ajuste para adicionar dias diferentes para cada receita

        Receita novaReceita = new Receita(valor, data, categoria);
        Lancamento l = new Lancamento();

        Object[] rowData = {l.lerArquivo()};
        tableModel.addRow(rowData);

        JOptionPane.showMessageDialog(this, "Receita salva:\nValor: " + novaReceita.getValor()
                + "\nData: " + novaReceita.getData()
                + "\nCategoria: " + novaReceita.getCategoria());
    }

    // Define o novo modelo da tabela
    jTable2.setModel(tableModel);

    // Limpa os campos após salvar
    textFieldValor.setText("");
    textFieldDia.setText("");
    textFieldMes.setText("");
    textFieldAno.setText("");
    jComboBoxCategoria.setSelectedIndex(0);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Por favor, insira valores válidos.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
} catch (IllegalArgumentException e) {
    JOptionPane.showMessageDialog(this, "Categoria de receita inválida.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField textFieldAno;
    private javax.swing.JTextField textFieldDia;
    private javax.swing.JTextField textFieldMes;
    private javax.swing.JTextField textFieldValor;
    // End of variables declaration//GEN-END:variables
}
